project:
  type: website
  # output directory used on gh-pages branch. format: YYMM
  output-dir: "results"
  render: 
    - "!README.md"
    - "!LICENSE"
    - "!LICENSE.md"
    - "!scripts"
    - "!tmprepo"
    - "!*.Rmd"
    - "!*.md"
    - "*.qmd"

website:
  favicon: "assets/images/cake_icon.png"
  navbar:
    logo: "assets/images/cake_club_logo.webp"
    logo-alt: "logo"
    right:
      - icon: "github"
        href: "https://github.com/ImmunTech/CakeClub"
  page-footer:
    border: false
    left: "{{< meta current_year >}} [NBIS](https://nbis.se) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  site-url: "https://nbisweden.github.io/workshop-data-visualization-r/2505/"
  open-graph: true

format:
  html:
    quarto-required: ">=1.4.0"
    theme: "assets/css/styles.scss"
    smooth-scroll: true
    toc: true
    toc-depth: 4
    toc-location: right
    number-sections: true
    number-depth: 4
    code-fold: false
    code-tools: false
    code-copy: true
    code-overflow: wrap
    df-print: paged
    standalone: false
    fig-align: left
    callout-icon: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    lightbox: auto
  revealjs:
    quarto-required: ">=1.4.0"
    theme: ["default","assets/css/slides.scss"]
    df-print: paged
    width: 1280
    height: 720
    transition: "fade"
    transition-speed: "fast"
    smaller: false
    incremental: false
    scrollable: false
    slide-level: 2
    slide-number: true
    progress: true
    date:  last-modified
    date-format: "DD-MMM-YYYY"
    fig-align: left
    chalkboard: true
    callout-icon: true
      
csl: apa.csl

knitr:
  opts_chunk:
    results: hold

execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: true

filters:
  - assets/custom.lua
  - assets/fold-results.lua
  - reveal-logo

# location is used to render the info page
# location options are linkoping, lund, umea, stockholm, uppsala or online
# one or more separated by commas or semicolon.
colors:
  primary: "#95b540"
  secondary: "#E9F2D1"


